// Code generated by gotemplate. DO NOT EDIT.

// Copyright (c) 2015, Emir Pasic. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package treeset implements a tree backed by a red-black tree.
//
// Structure is not thread safe.
//
// Reference: http://en.wikipedia.org/wiki/Set_%28abstract_data_type%29
package example

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/eosspark/container/templates"
	rbt "github.com/eosspark/container/trees/redblacktree"
	"github.com/eosspark/container/utils"
)

// template type Set(V,Compare)

func assertStringSetImplementation() {
	var _ templates.Set = (*StringSet)(nil)
}

// Set holds elements in a red-black tree
type StringSet struct {
	tree *rbt.Tree
}

type MultiStringSet struct {
}

var itemExistsStringSet = struct{}{}

// NewWith instantiates a new empty set with the custom comparator.

func NewStringSet(Value ...string) *StringSet {
	set := &StringSet{tree: rbt.NewWith(utils.StringComparator)}
	set.Add(Value...)
	return set
}

//func NewWith(comparator utils.Comparator, values ...V) *Set {
//	set := &Set{tree: rbt.NewWith(comparator)}
//	if len(values) > 0 {
//		set.Add(values...)
//	}
//	return set
//}

func CopyFromStringSet(ts *StringSet) *StringSet {
	return &StringSet{tree: rbt.CopyFrom(ts.tree)}
}

func StringSetIntersection(a *StringSet, b *StringSet, callback func(elem string)) {
	aIterator := a.Iterator()
	bIterator := b.Iterator()

	if !aIterator.First() || !bIterator.First() {
		return
	}

	comparator := a.GetComparator()

	for aHasNext, bHasNext := true, true; aHasNext && bHasNext; {
		comp := comparator(aIterator.Value(), bIterator.Value())
		switch {
		case comp > 0:
			bHasNext = bIterator.Next()
		case comp < 0:
			aHasNext = aIterator.Next()
		default:
			callback(aIterator.Value())
			aHasNext = aIterator.Next()
			bHasNext = bIterator.Next()
		}
	}
}

func (set *StringSet) GetComparator() utils.Comparator {
	return set.tree.Comparator
}

// Add adds the item one to the set.Returns false and the interface if it already exists
func (set *StringSet) AddItem(item string) (bool, string) {
	opt, k, _ := set.tree.PutItem(item, itemExistsStringSet)
	return opt, k.(string)
}

// Add adds the items (one or more) to the set.
func (set *StringSet) Add(items ...string) {
	for _, item := range items {
		set.tree.Put(item, itemExistsStringSet)
	}
}

// Remove removes the items (one or more) from the set.
func (set *StringSet) Remove(items ...string) {
	for _, item := range items {
		set.tree.Remove(item)
	}
}

// Contains checks weather items (one or more) are present in the set.
// All items have to be present in the set for the method to return true.
// Returns true if no arguments are passed at all, i.e. set is always superset of empty set.
func (set *StringSet) Contains(items ...string) bool {
	for _, item := range items {
		if _, contains := set.tree.Get(item); !contains {
			return false
		}
	}
	return true
}

// Empty returns true if set does not contain any elements.
func (set *StringSet) Empty() bool {
	return set.tree.Size() == 0
}

// Size returns number of elements within the set.
func (set *StringSet) Size() int {
	return set.tree.Size()
}

// Clear clears all values in the set.
func (set *StringSet) Clear() {
	set.tree.Clear()
}

// Values returns all items in the set.
func (set *StringSet) Values() []string {
	keys := make([]string, set.Size())
	it := set.Iterator()
	for i := 0; it.Next(); i++ {
		keys[i] = it.Value()
	}
	return keys
}

// String returns a string representation of container
func (set *StringSet) String() string {
	str := "TreeSet\n"
	items := []string{}
	for _, v := range set.tree.Keys() {
		items = append(items, fmt.Sprintf("%v", v))
	}
	str += strings.Join(items, ", ")
	return str
}

// Iterator returns a stateful iterator whose values can be fetched by an index.
type IteratorStringSet struct {
	index    int
	iterator rbt.Iterator
	tree     *rbt.Tree
}

// Iterator holding the iterator's state
func (set *StringSet) Iterator() IteratorStringSet {
	return IteratorStringSet{index: -1, iterator: set.tree.Iterator(), tree: set.tree}
}

// Next moves the iterator to the next element and returns true if there was a next element in the container.
// If Next() returns true, then next element's index and value can be retrieved by Index() and Value().
// If Next() was called for the first time, then it will point the iterator to the first element if it exists.
// Modifies the state of the iterator.
func (iterator *IteratorStringSet) Next() bool {
	if iterator.index < iterator.tree.Size() {
		iterator.index++
	}
	return iterator.iterator.Next()
}

// Prev moves the iterator to the previous element and returns true if there was a previous element in the container.
// If Prev() returns true, then previous element's index and value can be retrieved by Index() and Value().
// Modifies the state of the iterator.
func (iterator *IteratorStringSet) Prev() bool {
	if iterator.index >= 0 {
		iterator.index--
	}
	return iterator.iterator.Prev()
}

// Value returns the current element's value.
// Does not modify the state of the iterator.
func (iterator *IteratorStringSet) Value() string {
	return iterator.iterator.Key().(string)
}

// Index returns the current element's index.
// Does not modify the state of the iterator.
func (iterator *IteratorStringSet) Index() int {
	return iterator.index
}

// Begin resets the iterator to its initial state (one-before-first)
// Call Next() to fetch the first element if any.
func (iterator *IteratorStringSet) Begin() {
	iterator.index = -1
	iterator.iterator.Begin()
}

// End moves the iterator past the last element (one-past-the-end).
// Call Prev() to fetch the last element if any.
func (iterator *IteratorStringSet) End() {
	iterator.index = iterator.tree.Size()
	iterator.iterator.End()
}

// First moves the iterator to the first element and returns true if there was a first element in the container.
// If First() returns true, then first element's index and value can be retrieved by Index() and Value().
// Modifies the state of the iterator.
func (iterator *IteratorStringSet) First() bool {
	iterator.Begin()
	return iterator.Next()
}

// Last moves the iterator to the last element and returns true if there was a last element in the container.
// If Last() returns true, then last element's index and value can be retrieved by Index() and Value().
// Modifies the state of the iterator.
func (iterator *IteratorStringSet) Last() bool {
	iterator.End()
	return iterator.Prev()
}

// Each calls the given function once for each element, passing that element's index and value.
func (set *StringSet) Each(f func(index int, value string)) {
	iterator := set.Iterator()
	for iterator.Next() {
		f(iterator.Index(), iterator.Value())
	}
}

// Map invokes the given function once for each element and returns a
// container containing the values returned by the given function.
func (set *StringSet) Map(f func(index int, value string) string) *StringSet {
	newSet := &StringSet{tree: rbt.NewWith(set.tree.Comparator)}
	iterator := set.Iterator()
	for iterator.Next() {
		newSet.Add(f(iterator.Index(), iterator.Value()))
	}
	return newSet
}

// Select returns a new container containing all elements for which the given function returns a true value.
func (set *StringSet) Select(f func(index int, value string) bool) *StringSet {
	newSet := &StringSet{tree: rbt.NewWith(set.tree.Comparator)}
	iterator := set.Iterator()
	for iterator.Next() {
		if f(iterator.Index(), iterator.Value()) {
			newSet.Add(iterator.Value())
		}
	}
	return newSet
}

// Any passes each element of the container to the given function and
// returns true if the function ever returns true for any element.
func (set *StringSet) Any(f func(index int, value string) bool) bool {
	iterator := set.Iterator()
	for iterator.Next() {
		if f(iterator.Index(), iterator.Value()) {
			return true
		}
	}
	return false
}

// All passes each element of the container to the given function and
// returns true if the function returns true for all elements.
func (set *StringSet) All(f func(index int, value string) bool) bool {
	iterator := set.Iterator()
	for iterator.Next() {
		if !f(iterator.Index(), iterator.Value()) {
			return false
		}
	}
	return true
}

// Find passes each element of the container to the given function and returns
// the first (index,value) for which the function is true or -1,nil otherwise
// if no element matches the criteria.
func (set *StringSet) Find(f func(index int, value string) bool) (idx int, v string) {
	iterator := set.Iterator()
	for iterator.Next() {
		if f(iterator.Index(), iterator.Value()) {
			return iterator.Index(), iterator.Value()
		}
	}
	return -1, v
}

// ToJSON outputs the JSON representation of the set.
func (set *StringSet) ToJSON() ([]byte, error) {
	return json.Marshal(set.Values())
}

// FromJSON populates the set from the input JSON representation.
func (set *StringSet) FromJSON(data []byte) error {
	elements := []string{}
	err := json.Unmarshal(data, &elements)
	if err == nil {
		set.Clear()
		set.Add(elements...)
	}
	return err
}
